sudo: required
services:
  - docker
before_install:
  - docker build -t olyabelome/docker-web -f Dockerfile.dev .
script:
  - docker run -e CI=true olyabelome/docker-web npm run test
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-web'
  env: 'DockerWeb-env'
  bucket_name: 'elasticbeanstalk-us-east-2-246543545294'
  bucket_path: 'docker-web'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
